### ISSUE TITLE
Error with token refresh

### ISSUE THREAD

**Issue by jgwerner** [3Blades/openapi#112]
During a token refresh using endpoint `/auth/jwt-token-refresh/`, backend returns:

```
{
"non_field_errors": [
"orig_iat field is required."
  ]
}
```
3Blades/app-backend#307

**Comment by jgwerner** [comment]
This doesn't seem to be a documentation issue but will close once API test has passed.

**Comment by jgwerner** [comment]
@jkp85 @johngriebel could you shed some light on proper behavior for this endpoint?

**Comment by jkp85** [comment]
@jgwerner It was fixed here https://github.com/3Blades/app-backend/commit/a6a974b5a6e9ba436a4c8abedf976b0879836c67 it should be ok because of https://github.com/GetBlimp/django-rest-framework-jwt/blob/master/rest_framework_jwt/utils.py#L56

**Comment by jgwerner** [comment]
Validated fix.
