### ISSUE TITLE
Card replacement and update cannot accept token parameter

### ISSUE THREAD

**Issue by jgwerner** [3Blades/openapi#132]
Server error when attempting to update/replace a credit card when token parameter has a value. When updating or replacing without this value, then the request/response is successful.

Server response when [token parameter has a value assigned to it](https://stripe.com/docs/testing#cards):

```
InvalidRequestError at /v1/greg/billing/cards/d82d366f-7aa6-446a-a49c-0043e38f15e2/
Request req_3LhG6cN22ZqtcA: Received unknown parameter: token

Request Method: PUT
Request URL: http://dev-api.3blades.ai/v1/greg/billing/cards/d82d366f-7aa6-446a-a49c-0043e38f15e2/
Django Version: 1.11.5
Python Executable: /srv/env/bin/python3
Python Version: 3.6.2
Python Path: ['/srv/env/lib/python3.6/site-packages/git/ext/gitdb', '/srv/app', '/srv/env/bin', '/srv/env/lib/python36.zip', '/srv/env/lib/python3.6', '/srv/env/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6', '/srv/env/lib/python3.6/site-packages', '/srv/app', '/srv/env/lib/python3.6/site-packages/gitdb/ext/smmap']
```

It seems that updating or replacing a credit card does not allow updating or replacing the token, so we need to remove this parameter from swagger for PUT and PATCH methods.

/cc @johngriebel

**Comment by johngriebel** [comment]
@jgwerner Is there any easy way to show `token` as a field for `POST` only? I'm looking at this now and the best thing I can see to do is just to add a note on the `token` field for CardData.

**Comment by jgwerner** [comment]
@johngriebel yes, we can add `token` field to `POST` only. We would just have to add a new model in `definitions` that does not include `token`.

**Comment by jgwerner** [comment]
Done.
