### ISSUE TITLE
Update subscription name parameter

### ISSUE THREAD

**Issue by jgwerner** [3Blades/openapi#133]
Billing subscription `name` parameter tells the user to add a plan name string when it actually requires the plan's UUID. Update docs to clarify.

**Comment by jgwerner** [comment]
@johngriebel since just changing the description of the `plan` field to specify that it must contain a UUID is not enough (in my opinion), would you be ok with changing the property name from `id` to `plan_id`? In that case, responses would look like so:

```
[{"id": "579208c3-4f5c-4b5d-baa3-309a06db681c","plan_id": "efb36cb0-0ef2-4af3-ae5d-10d9ae73845d","stripe_id": "sub_B5KyO9BZ6lUNPP","created": "2017-07-24T17:25:04Z","livemode": false,"application_fee_percent": 0,"cancel_at_period_end": false,"canceled_at": "","current_period_start": "2017-07-24T17:25:04Z","current_period_end": "2017-07-31T17:25:04Z","start": "2017-07-24T17:25:04Z","ended_at": "","quantity": 1,"status": "trialing","trial_start": "2017-07-24T17:25:04Z","trial_end": "2017-07-31T17:25:04Z"}]
```

**Comment by johngriebel** [comment]
@jgwerner, yes I think that's the way to go

**Comment by jgwerner** [comment]
No longer applicable. We just need to update summary to state that plan name accepts unique identifier.
