### ISSUE TITLE
Modify summary for server terminate

### ISSUE THREAD

**Issue by jgwerner** [3Blades/openapi#137]
Terminating a server does not mean deleting a server. Modify summary for server/terminate endpoint to reflect this.

#142

**Comment by johngriebel** [comment]
@jgwerner what _does_ `terminate` mean? Is it the same as `stop`? If so, why have two endpoints?

**Comment by jgwerner** [comment]
@johngriebel `terminate` means stopping and then removing the server container in one step. `stop` means stopping the container, which technically still sequesters instance resources. If a user were to install custom packages, then a server stop would leave the customizations intact within the container. If the user installed custom packages and then terminated server, the user would lose customizations, unless there was an additional feature to commit and save a custom image in a registry.

Unlike Docker Swarm classic, Docker Swarm Mode does not have the concept of `stop`. Both Docker Swarm Mode and Docker Swarm classic have `terminate` as an option but they call it differently (`docker service rm <service name>` and `docker -H <manager ip:port> rm <container>`, respectively).

The documentation leads the user to believe that selecting the terminate option deletes the server entirely, and although that may be true, we need to provide more clarification that it does not mean deleting server-size record...at least that is my impression.

**Comment by jgwerner** [comment]
Done.
