### ISSUE TITLE
Expand on swagger documentation

### ISSUE THREAD

**Issue by jgwerner** [3Blades/openapi#29]
Add:

- Summary for each endpoint, using the summary object. This will add a friendlier view when exploring API via docs.
- Example responses by adding example object in the response object.
- Additional error models.
- [Add PHP](https://readme.readme.io/docs/swagger-extensions#section-code-sample-languages) using `x-samples-languages`
- Add [static headers](https://readme.readme.io/docs/swagger-extensions#section-static-headers)

**Comment by jgwerner** [comment]
@jkp85 @raygesualdo @roachmd I'm going to change referencies to primary keys to ID's in endpoints, like so: 

    `.../project/{project_pk}/...`
    `.../servers/{server_pk}/...` 

Agree?

**Comment by raygesualdo** [comment]
Yep, where there's not another `id` for it to conflict with (e.g. `/{namespace}/projects/{project_pk}/project_files/{id}/`).

**Comment by jgwerner** [comment]
@johngriebel agree on `basePath: /v1` for base path?

    https://api.3blades.ai/v1/...

**Comment by jgwerner** [comment]
Additional requirement: lets leave baseUrl with `../` active but use that to return what versions are available with tag, such as `EXPERIMENTAL`. I saw this when looking at some [Swagger examples](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/api-with-examples.json) and thought it would be a good idea.

**Comment by jgwerner** [comment]
Done.
