### ISSUE TITLE
Stats and Runstats Corrections

### ISSUE THREAD

**Issue by pthakkar230** [3Blades/openapi#83]
Based on the Runscope testing, it looks like that we don't need to have the `GET`, `PUT`, `PATCH`, and `DELETE` methods for `stats` or `run-stats` based on their `id`. The only thing needed is to create the stats and then use the `GET` method to retrieve the stats without passing in the `id`.

More info in this closed issue: https://github.com/3Blades/app-backend/issues/224

Thoughts? @johngriebel 
CC @jgwerner @roachmd

**Comment by jgwerner** [comment]
@jkp85 @johngriebel what do you think of this proposal?

**Comment by jgwerner** [comment]
Duplicate of #116
